name: Publish

on:
  release:
    types:
      - published

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install set-cargo-version
      run: cargo install set-cargo-version

    - name: Version
      run: set-cargo-version ./Cargo.toml ${{ github.event.release.tag_name }}

    - name: Package
      # --allow-dirty because Cargo.toml has an uncommitted version update.
      run: cargo package --allow-dirty

    - name: Login
      run: cargo login ${{ secrets.CRATES_IO_API_KEY }}

    - name: Publish
      # --allow-dirty because Cargo.toml has an uncommitted version update.
      run: cargo publish --allow-dirty

    - name: Logout
      run: cargo logout
