name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint style
        run: cargo fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            test_files
          key: ${{ runner.os }}-${{ hashFiles('.env', 'Cargo.lock') }}

      - name: Check
        run: cargo check --verbose

      - name: Analyze
        run: cargo clippy

      - name: Download test files
        run: ./download_test_files.sh

      - name: Test
        run: cargo test --verbose

      # The artifact doesn't get used; we're just checking if we can.
      - name: Package
        run: cargo package

  test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify project
        run: cargo verify-project
